type Comment {
    id: Int
    avatar: String
    name: String
    isTop: Boolean
    content: String
    publishDate: String
    commentNum: Int
    praiseNum: Int
}

type Query {
    comment: [Comment]
}

type Mutation {
    praise(id: Int): Int
}